# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: serverless-maestro

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.maestro
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: maestro
          method: post
          cors: true
